# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9b6156b429b25cc59a99c0f9946ab4a95c2e72d837a641e888f2729c08e93f56bbaf3edb817f5698be47bc3cc575de38c1be0e1b53ed7c7aa22ab72cfd25661

test:
  secret_key_base: 6520f783bcb382e802782b76fa14ec907a9ef96130943b62be9b0ce46ec988a2f51d43b629823e694b18cf36e75bb7e7d4c430aae42c86d3451df8f8c2aeaf42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
